### ISSUE TITLE
Feature Request: Dot filtering disable

### ISSUE THREAD

**Issue by wiesshund** [vbousquet/flexdmd#12]
This is not a bug, but a feature request

Would it be possible to have FlexDMD disable the dot mask and filtering entirely
and display when it is being given, just as it sees it, with out the DMD type post processing?

I realize that for a PinDMD or Pin2DMD this would be absolutely useless

but on an LCD display, it could be a simple fast and light weight alternative to resorting to PUP
Flex, a person unzips, runs 1 app, clicks 2 buttons and it works, end of story
PUP, not so much.

And table programming with flex is so much simpler, again, it simply just works, and can even be done using ultraDMD language
everything works right from the table scripts, what to play, when, for how long, can continually inject info to it, like scores or event messages

Be great if you could have the script do FlexDMD.DOTfilterProcessing = False

PS: sorry i could not find the discussion or features area, only bugs
so feel free to close this after you see it

**Comment by vbousquet** [comment]
Dot filtering is performed by DMDDevice (Freezy's DMD) not FlexDMD. So it fully rely on the configuration of DMDDevice (if you want, you can try the alternative renderer I have proposed for DMDDevice; it allows plain square dots without any type of filtering). I will close this issue for now since it does not seem to be linked with FlexDMD but DMDDevice
