### ISSUE TITLE
PinballY Manufacturer-Animation shows only 1 frame with flexdmd 1.8.0

### ISSUE THREAD

**Issue by fR33Styler-1971** [vbousquet/flexdmd#20]
Salut Vincent,

thank you very much for your development into 1.8.0 -  i like it a lot.

I have a little issue... since 1.8.0 (worked before) in PinballY with main.js Script, the animation (GIFs) from the manufacturer logos only show the 1st frame now (so no animation is shown anymore).

If i exchange (only) the FlexDMD.dll with 1.7.1 it works again.

Best regards
Ralf

**Comment by vbousquet** [comment]
This is most likely because you take a bad 1.8.0 release. This is my bad. I upload a wrong build, then replaced it with the right one. If you re-downaload or take the latest automatic build Github actions, everything should be fine again. I will close for now, but if the fix does not work, please reopen !

Regards
