### ISSUE TITLE
Flex DMD 1.9 Text Alignment Issues

### ISSUE THREAD

**Issue by alaw-lufc** [vbousquet/flexdmd#33]
Using https://github.com/vbousquet/flexdmd/actions/runs/4332019741 the text does not always align correctly. This appears to only affect tables that use external files (like a flexdmd folder in the visual pinball\tables folder)

E.g. Blood Machines V2.0 using the FlexDMD option, just setting up a two player game - look at the 00 score in the top left

V1.9
![image](https://user-images.githubusercontent.com/73988577/226610435-7f65d1fd-7891-48cc-b06b-6cbc0a5976ce.png)

V1.8
![image](https://user-images.githubusercontent.com/73988577/226610761-6be27890-c523-4fa0-8dde-a354148430f9.png)

**Comment by MikedaSpike** [comment]
I see the same problem with FLEXDMD within Visual Pinball when text is created from external path images.
This example is a Flexed DMD converison of bonebusters.

When using a folder with the font :
The text lines (2 rows of text line) will switch and show on the wrong location 👍🏻 
![image](https://user-images.githubusercontent.com/48748234/230539339-f38a2eda-a676-4c88-95ca-768008d0ec81.png)

As Scutters changed the code to use 'internal' VP images, the problem was solved, but still multiple tables uses a path to th eimages
