### ISSUE TITLE
FlexDMD Issue??

### ISSUE THREAD

**Issue by studlygoorite** [vbousquet/flexdmd#34]
Hi, I am running everything 64bit with a 32bit build (that I no longer use) side by side. I am seeing several FlexDMD errors with tables in VR only and wonder if anyone can make sense of the errors. I am running the latest FlexDMD 1.9 and the install shows all checkmarks and the VR-GL 64 bit v913 (I see Mike Da Spike has posted a similar issue over at the vpinball Github)

The last couple have said this....

   FlexDMD.log error....Abnormally long elapsed time between frames of 0.1065902s (rendering lasted 106.59ms, sleeping was 0ms), limiting to 66ms 
   
   And a script error......line 3580 "Asked to load a bitmap from a resource type unknown" 
With the script line reading ".AddActor FlexDMD .NewImage ("Back". "VPX.DMD_Background")

Any help would be greatly appreciated. Note, that I use a PInDMD3 and have virtualDMD set to false in my DmdDevice.ini

**Comment by MikedaSpike** [comment]
The error : 
```
Asked to load a bitmap from a resource type unknown
With the script line reading ".AddActor FlexDMD .NewImage ("Back". "VPX.DMD_Background")
```
Is not caused by FlexDMD, but bij VPX that is not able to read the FLEXDMD images when using images from the image library of VPX.
Using an older revision of 10.8 makes this table works.
If the images are moved from internal VP images to external images, the table is working as well.

Not sure if the timeout is caused , because it cannot load the images from the VP table or if thats another (extra) issue

I hope this can be fixed
