### ISSUE TITLE
virtualdmd rendered very blotchy

### ISSUE THREAD

**Issue by maartenlangeveld** [vbousquet/flexdmd#35]
Having installed FlexDMD (v1.8.0), DMD Extensions (v2.0.0) on my Win 11 PC with Visual Pinball, the virtual dmd is not rendered well.

![Screenshot 2023-04-20 122931](https://user-images.githubusercontent.com/47125471/233340329-47442b33-c796-45de-8382-c5bbbde2aa20.png)

**Comment by vbousquet** [comment]
The virtual DMD is not rendered by FlexDMD ; FlexDMD generate the dots which are rendered by your virtual DMD solution (like Freezy's DMDExt or others). Therefore, I won't be able to help you on this problem

**Comment by maartenlangeveld** [comment]
Hi @vbousquet 
Thanks, good to know! Will address the issue elsewhe.
Maarten

**Comment by wiesshund** [comment]
> 

Hi maartenlangveld

Your issue is you need to adjust the style (function of freezy's, right click the DMD)

Yours looks like that due to the dot size, and dot shape
You have to tune the style depending on the physical DMD window size.

Unless ALL DMD displays look like that, flexDMD AND ROM DMD's i would save the style for the table rather than save globally

And before editing a style, make sure to name a new style, rather than irreversably editing the default style.

**Comment by maartenlangeveld** [comment]
Hi @wiesshund,

Thanks for your reaction, really appreciate! However it is in my humble opinion not a matter of styling but has to do that I output my virtualdmd to the same screen as I play my tables (desktop mode). I only have a one display system. I guess the DMD output by dmdextensions is a borderless window on top that is being scaled up by windows scaling. When I set windows scaling to 100% in Windows 11 settings everything is fine, but it is a bit cumbersome to set windows scaling to 100% (normal 200%) on my 4k screen every time I want tot play.

I did set "override high dpi scaling behaviour" in the compatibility tab of the VpinballX.exe properties to have Vpinball override the Windows scaling. That worked for a while but for some reason it does not anymore (Windows) issue?

It would be fine if dmddevice.dll could override the Windows scaling settings.
