### ISSUE TITLE
Modded JPSalas Tables

### ISSUE THREAD

**Issue by uncmonky** [vbousquet/flexdmd#5]
When using the instructions for using FlexDMD with JPSalas' tables (e.g. "Miraculous") it works flawlessly.

When using the same instructions for using FlexDMD with a **_modified_** table **_based_** on JPSalas' tables (e.g. "The Last Unicorn") I get an error.

the code

> If Not FlexDMD is Nothing Then DMDScene.GetImage("Back").Bitmap = FlexDMD.NewImage("", "VPX." & dLine(2) & "&dmd=2").Bitmap

returns the error

> Object reference not set to an instance of an object.

Any advice on how I can make it work?

**Comment by vbousquet** [comment]
There are 2 things involved:
- first you need to adapt the script the same way as for Miraculous. I have commited the modification on GitHub, you can find it in the Script folder.
- second, there was a bug in FlexDMD which would not let him use the image used in The Last Unicorn since there are palette indexed images (other tables use more traditionnal format). I have fixed FlexDMD to support these images as well. You can test the new version with this (prerelease): [FlexDMD 1.5.0.zip](https://github.com/vbousquet/flexdmd/files/5121912/FlexDMD.1.5.0.zip)

Please report here, if the provided elements fix the issue. Regards

**Comment by uncmonky** [comment]
Excellent! Thank you very much.

**Comment by uncmonky** [comment]
M Bosquet:

The revisions you made are perfect. I can report that I have tested it
successfully with 3 total modified JP Salas tables by Marcade/Mark Paulik
(Last Unicorn, Dark Crystal and Ghostbusters).
May I share the zip file you sent to me on VPForums.org in this thread?

https://www.vpforums.org/index.php?showtopic=45010#entry457533

Thank you,
David Polston

**Comment by vbousquet** [comment]
@uncmonky I will be releasing the 1.5 version soon. I would prefer to avoid having the prerelease advertised too much for the moment since it will confuse people when the real 1.5 will be out, but you can put a link to the page of this issue: https://github.com/vbousquet/flexdmd/issues/5. I just have a few other little improvments to pack in and it should be out int he coming week.

**Comment by vbousquet** [comment]
@uncmonky I have just released a clean 1.5 version. Feel free to speak about it. Regards
